In [1]:
import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # 배열 : 원소는 모두 같은 타입, 원소의 갯수는 변경하지 못함.

In [3]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(ar)

numpy.ndarray

## 벡터화 연산
배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리함

In [8]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x # 요소에 대한 반복 없이 한번에 연산 x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 10

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10) # ?

array([False,  True, False])

In [17]:
# 2차원 배열
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
len(c)

2

In [19]:
len(c[0])

3

### 연습문제

In [37]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

- - -

In [24]:
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]])
d # 3차원 2 * 3 * 4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [25]:
print(d.ndim) # 배열의 차원
print(d.shape) # 배열의 크기

3
(2, 3, 4)


In [28]:
# 다차원 배열 접근 (쉼표로)
d[0,1,2]

7

In [29]:
d[-1, -1, -1] # 마지막 원소

22

## 슬라이싱

In [31]:
# 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
a[0, :]

array([0, 1, 2, 3])

In [33]:
a[1, :]

array([4, 5, 6, 7])

In [34]:
a[:, 1] # 두번째 열 

array([1, 5])

In [35]:
a[1, 1:] # 두번째 행의 두번째 열부터 

array([5, 6, 7])

In [36]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

### 연습문제

In [39]:
m = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
m[1, 2]

7

In [41]:
m[-1, -1]

14

In [43]:
m[1, 1:3]

array([6, 7])

In [45]:
m[1:,2]

array([ 7, 12])

In [46]:
m[:-1, -2:]

array([[3, 4],
       [8, 9]])

- - -

## 배열 인덱싱
데이터베이스의 질의 기능을 수행함. 인덱스 배열: 불리언 배열 방식, 정수 배열 방식

In [48]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [49]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [50]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [51]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [52]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8]) # 정수 배열 인덱싱
a[idx]

array([11, 33, 55, 77, 99])

In [53]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [56]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### 연습문제

In [57]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
y = x[x % 3 == 0]
y

array([ 3,  6,  9, 12, 15, 18])

In [74]:
y[y % 4 == 1]

array([9])