In [1]:
# seed 시드를 통해 난수 처럼 보이는 수열을 생성함. 

In [5]:
np.random.seed(0) # 시드 설정

In [6]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [7]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

### 데이터 순서 바꾸기

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.shuffle(x)
x

array([7, 8, 3, 6, 1, 5, 0, 4, 9, 2])

### 데이터 샘플링 
일부를 무작위로 선택함


In [14]:
np.random.choice(5, 5, replace=False) # replace True면 한번 선택한 데이터 다시 선택 가능함

array([0, 1, 4, 2, 3])

In [15]:
np.random.choice(5, 3, replace=False)

array([1, 3, 0])

In [16]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([4, 0, 4, 1, 4, 1, 2, 2, 0, 1])

In [17]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 확률 추가

array([3, 0, 3, 3, 2, 2, 2, 2, 3, 3])

 ### 난수 생성

In [19]:
np.random.rand(10) # 0~1

array([0.65632959, 0.13818295, 0.19658236, 0.36872517, 0.82099323,
       0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ])

In [20]:
np.random.rand(3, 5)

array([[0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805]])

In [22]:
np.random.randn(10) # 기댓값 0, 표준편차 1-> 가우시안 표준 정규 분포를 따르는 난수

array([ 0.92525075, -0.90478616,  1.84369153,  1.52550724, -1.44553558,
        0.37716061, -0.07055723,  0.60415971,  0.472149  ,  0.81991729])

In [23]:
np.random.randn(3, 5)

array([[ 9.07519617e-01, -5.85822875e-01,  9.37558842e-01,
        -2.54608092e-01,  9.73598712e-01],
       [ 2.07282772e-01,  1.09964197e+00,  9.39896981e-01,
         6.06389001e-01,  1.76084071e-03],
       [-9.90160143e-01,  1.87239408e+00, -2.41073590e-01,
         5.33449070e-02,  1.03081595e+00]])

In [25]:
np.random.randint(10, size=10) #  0-10 숫자

array([8, 8, 3, 2, 3, 6, 3, 6, 5, 7])

In [26]:
np.random.randint(10, 20, size=10) # 10 과 20 사이의 숫자

array([10, 18, 14, 16, 15, 18, 12, 13, 19, 17])

In [27]:
np.random.randint(10, 20, size=(3,5))

array([[15, 13, 14, 15, 13],
       [13, 17, 19, 19, 19],
       [17, 13, 12, 13, 19]])

### 정수 데이터 카운팅

In [29]:
np.unique([11, 11, 2, 2, 34, 34]) # 중복된 값을 제거, 중복되지 않는 값의 리스트 출력

array([ 2, 11, 34])

In [30]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)

In [31]:
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [32]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [33]:
count

array([2, 2, 1])

In [34]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 주사위를 던졌을 때 나온 수 , 한번도 없으면 카운트 값 : 0

array([0, 2, 3, 1, 0, 0])