### 벡터화 연산
벡터화 연산을 사용하면 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 연산을 할 수 있음

In [1]:
a = np.arange(1, 10001)
b = np.arange(10001, 20001)

In [3]:
z = a + b
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

a == b

array([False,  True, False,  True])

In [5]:
a >= b

array([False,  True,  True,  True])

In [6]:
c = np.array([1, 2, 3, 4])

In [7]:
np.all(a == b)

False

In [9]:
np.all(a == c)

True

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:

x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅
벡터끼리 연산하기 위해선 벡터의 크기가 같아야함.  
서로 다른 크기를 가진 두 배열의 사칙연산을 지원하는 것

In [22]:
x = np.arange(5)
y = np.ones_like(x)

In [23]:
x + y

array([1, 2, 3, 4, 5])

In [24]:
x + 1

array([1, 2, 3, 4, 5])

In [33]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [34]:
[range(7)[i:i + 3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [35]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a.min()

0

In [41]:
a.max()

9

In [42]:
a.sum()

45

In [43]:
a.argmin()

0

In [44]:
a.argmax() # max값의 인덱스 

9

In [45]:
a.mean()

4.5

In [46]:
np.median(a)

4.5

In [48]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.all([True, False]) # and

False

In [53]:
np.any([True, False]) # or

True

In [54]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [55]:
np.any(a != 0)


False

In [56]:
np.all(a == a)


True

In [57]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [58]:
((a <= b) & (b <= c)).all()

True

In [59]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [60]:
x.sum()

6

In [61]:
x.sum(axis=0) # 열의 합계

array([3, 3])

In [62]:
x.sum(axis=1) # 행의 합계

array([2, 4])

### 연습문제

In [68]:
a = np.arange(30, dtype='f')
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.], dtype=float32)

In [78]:
a = a.reshape(5, 6)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]], dtype=float32)

In [75]:
a.mean()

14.5

In [77]:
a.sum(axis=0)

array([60., 65., 70., 75., 80., 85.], dtype=float32)

In [79]:
a.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5], dtype=float32)

### 정렬

In [80]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [82]:
a.sort()
a # axis = -1, axis = 1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [85]:
np.sort(a, axis=0) 

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [88]:
a.sort(axis=0)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [90]:
# 순서만 알고 싶을 때
a = np.array([40, 76, 12, 38])
np.argsort(a)

array([2, 3, 0, 1])

### 연습문제


In [92]:
arr = np.array([[  1,    2,    3,    4], [ 46,   99,  100,   71],[ 81,   59,   90,  100]])

In [93]:
np.sort(arr)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [94]:
np.sort(arr, axis=1) # 이게 맞는 듯

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [96]:
np.sort(arr, axis=0)

array([[  1,   2,   3,   4],
       [ 46,  59,  90,  71],
       [ 81,  99, 100, 100]])

In [99]:
np.sort(arr)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])